// Code generated by "stringer -type builtinfunc builtinfunc.go"; DO NOT EDIT.

package gotype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[builtinfuncInt-1]
	_ = x[builtinfuncPtrItem-2]
	_ = x[builtinfuncItem-3]
	_ = x[builtinfuncInterface-4]
	_ = x[builtinfuncVoid-5]
}

const _builtinfunc_name = "builtinfuncIntbuiltinfuncPtrItembuiltinfuncItembuiltinfuncInterfacebuiltinfuncVoid"

var _builtinfunc_index = [...]uint8{0, 14, 32, 47, 67, 82}

func (i builtinfunc) String() string {
	i -= 1
	if i >= builtinfunc(len(_builtinfunc_index)-1) {
		return "builtinfunc(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _builtinfunc_name[_builtinfunc_index[i]:_builtinfunc_index[i+1]]
}
