// Code generated by "stringer -type builtinfunc builtinfunc.go"; DO NOT EDIT.

package gotype

import "strconv"

const _builtinfunc_name = "builtinfuncIntbuiltinfuncPtrItembuiltinfuncItembuiltinfuncInterfacebuiltinfuncVoid"

var _builtinfunc_index = [...]uint8{0, 14, 32, 47, 67, 82}

func (i builtinfunc) String() string {
	i -= 1
	if i >= builtinfunc(len(_builtinfunc_index)-1) {
		return "builtinfunc(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _builtinfunc_name[_builtinfunc_index[i]:_builtinfunc_index[i+1]]
}
