// Code generated by "stringer -type ChanDir chandir.go"; DO NOT EDIT.

package gotype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RecvDir-1]
	_ = x[SendDir-2]
	_ = x[BothDir-3]
}

const _ChanDir_name = "RecvDirSendDirBothDir"

var _ChanDir_index = [...]uint8{0, 7, 14, 21}

func (i ChanDir) String() string {
	i -= 1
	if i < 0 || i >= ChanDir(len(_ChanDir_index)-1) {
		return "ChanDir(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ChanDir_name[_ChanDir_index[i]:_ChanDir_index[i+1]]
}
